name: test coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.23.5"

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests and generate coverage
      run: go test -v -coverprofile=coverage.out ./...

    - name: Check coverage
      id: coverage
      run: |
        coverage=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
        echo "total_coverage=$coverage" >> $GITHUB_OUTPUT
        echo "Coverage: $coverage%"
      
    - name: Fail if coverage is below threshold
      run: |
        if (( $(echo "$total_coverage < 50" | bc -l) )); then
          echo "Coverage ($total_coverage%) is below the threshold (50%)"
          exit 1
        fi